// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkMfUokuE8d5Wut5litxhHDjmPm-sSVkY',
    appId: '1:344121608635:android:81f62818a042728dd65c9e',
    messagingSenderId: '344121608635',
    projectId: 'citizen-wallet-b1262',
    storageBucket: 'citizen-wallet-b1262.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmaPtoo8Z-kMnYF_7eQYX-s9K-HlIzv8E',
    appId: '1:344121608635:ios:c0ca8f95084443d4d65c9e',
    messagingSenderId: '344121608635',
    projectId: 'citizen-wallet-b1262',
    storageBucket: 'citizen-wallet-b1262.appspot.com',
    iosBundleId: 'xyz.citizenwallet.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmaPtoo8Z-kMnYF_7eQYX-s9K-HlIzv8E',
    appId: '1:344121608635:ios:c0ca8f95084443d4d65c9e',
    messagingSenderId: '344121608635',
    projectId: 'citizen-wallet-b1262',
    storageBucket: 'citizen-wallet-b1262.appspot.com',
    iosBundleId: 'xyz.citizenwallet.wallet',
  );
}
